### PR TITLE
Fix the unhandled error when unable to connect.

### LINKED ISSUE #52: Schema file not checked into source control
The new schema is not stored in source control which means that any changes to anything outside of the generator requires the editor to build the schema from the Juju source again and then build this project. This can be tedious and challenging for someone new to the project. We should probably include the schema file in the source tree for the current version released on npm.

### PR DESCRIPTION
**Pull request by hatched**
If the script is unable to connect then reject the connection attempt to allow the user script to handle the connection failure.

Fixes #52 

This version has been built and released to npm under the beta tag. See the associated PR in the jaas-dashboard for QA.

### CODE REVIEW

File: api/client.ts [hunk 1]
```diff
@@ -155,7 +155,7 @@ function connectAndLogin(url: string, credentials, options) {
       const conn = await juju.login(credentials);
       resolve({ conn, logout: juju.logout.bind(juju) });
     } catch (error) {
-      if (!juju.isRedirectionError(error)) {
+      if (!juju || !juju.isRedirectionError(error)) {
```
Comment (hatched) [inline api/client.ts:158]: This is the fix for the connection error, the rest is to add the schema to the source tree.

**Review by barrymcgee — APPROVED** [review]
